export function handleError(error) {
    console.log("Something went wrong:")
    console.log(error)
}